# docker/predixy/conf/predixy.conf
Name PredixyExample

Bind 0.0.0.0:7617

ClientTimeout 300

LogVerbSample 0
LogDebugSample 0
LogInfoSample 10000
LogNoticeSample 1
LogWarnSample 1
LogErrorSample 1

Authority {
    Auth {
        Mode write
    }
    Auth "#a complex password#" {
        Mode admin
    }
}

ClusterServerPool {
    Password redis_password
    MasterReadPriority 60
   StaticSlaveReadPriority 50
    DynamicSlaveReadPriority 50
    RefreshInterval 1
    ServerTimeout 1
   ServerFailureLimit 10
    ServerRetryTimeout 1
    KeepAlive 120
    Servers {
        + redis-node-1:6379
        + redis-node-2:6379
        + redis-node-3:6379
    }
}

Include latency.conf
